In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import torch
from torch import tensor

In [2]:
def matmul(a,b):
    ar,ac = a.shape # n_rows * n_cols
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): c[i,j] += a[i,k] * b[k,j]
    return c

In [25]:
m1 = torch.randn(5,28*28)
m2 = torch.randn(784,10)

In [4]:
%time t1=matmul(m1, m2)

CPU times: user 788 ms, sys: 1.98 ms, total: 790 ms
Wall time: 820 ms


In [5]:
%timeit -n 20 t2=m1@m2

The slowest run took 114.88 times longer than the fastest. This could mean that an intermediate result is being cached.
89.8 µs ± 207 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [6]:
a = tensor([10., 6, -4])
b = tensor([2., 8, 7])
a + b

tensor([12., 14.,  3.])

In [7]:
a < b

tensor([False,  True,  True])

In [8]:
(a + b).mean().item()

9.666666984558105

In [9]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
m*m

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [10]:
n = tensor([[1., 2, 3], [4,5,6]])
m*n

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [4]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc): c[i,j] = (a[i] * b[:,j]).sum()
    return c

In [12]:
%timeit -n 20 t3 = matmul(m1,m2)

1.08 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


**Broadcasting Examples**

In [13]:
a = tensor([10., 6, -4])
a > 0

tensor([ True,  True, False])

In [14]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
(m - 5) / 2.73

tensor([[-1.4652, -1.0989, -0.7326],
        [-0.3663,  0.0000,  0.3663],
        [ 0.7326,  1.0989,  1.4652]])

In [5]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3]))

In [6]:
m + c

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [7]:
c.expand_as(m)

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [8]:
t = c.expand_as(m)
t.storage()

/tmp/ipykernel_33/3696445842.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  t.storage()


 10.0
 20.0
 30.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [9]:
t.stride(), t.shape

((0, 1), torch.Size([3, 3]))

In [10]:
c + m

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [11]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6]])
c+m

tensor([[11., 22., 33.],
        [14., 25., 36.]])

In [12]:
c = tensor([10.,20])
m = tensor([[1., 2, 3], [4,5,6]])
c+m

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [16]:
c = tensor([10.,20,30])
c.shape

torch.Size([3])

In [17]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
c+m

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [18]:
c = c.unsqueeze(1)
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3, 1]))

Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

In [14]:
??c.unsqueeze

Docstring:
unsqueeze(dim) -> Tensor

See :func:`torch.unsqueeze`
Type:      builtin_function_or_method

In [15]:
c+m

tensor([[11., 12., 13.],
        [24., 25., 26.],
        [37., 38., 39.]])

In [19]:
t = c.expand_as(m)
t.storage()

 10.0
 20.0
 30.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [20]:
t.stride(), t.shape

((1, 0), torch.Size([3, 3]))

In [21]:
c = tensor([10.,20,30])
c.shape, c.unsqueeze(0).shape,c.unsqueeze(1).shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [22]:
c.shape, c[None,:].shape,c[:,None].shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [23]:
c[None].shape,c[...,None].shape

(torch.Size([1, 3]), torch.Size([3, 1]))

In [24]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
#       c[i,j] = (a[i,:]          * b[:,j]).sum() # previous
        c[i]   = (a[i  ].unsqueeze(-1) * b).sum(dim=0)
    return c

In [26]:
%timeit -n 20 t4 = matmul(m1,m2)

214 µs ± 116 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [27]:
def matmul(a,b): return torch.einsum('ik,kj->ij', a, b)

In [28]:
%timeit -n 20 t4 = matmul(m1,m2)

The slowest run took 117.84 times longer than the fastest. This could mean that an intermediate result is being cached.
572 µs ± 1.32 ms per loop (mean ± std. dev. of 7 runs, 20 loops each)


**Building the NN**

In [ ]:
def lin(x, w, b): return x @ w + b