In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import torch
from torch import tensor

In [4]:
def matmul(a,b):
    ar,ac = a.shape # n_rows * n_cols
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): c[i,j] += a[i,k] * b[k,j]
    return c

In [5]:
m1 = torch.randn(5,28*28)
m2 = torch.randn(784,10)

In [6]:
%time t1=matmul(m1, m2)

CPU times: user 781 ms, sys: 3.48 ms, total: 784 ms
Wall time: 823 ms


In [7]:
%timeit -n 20 t2=m1@m2

The slowest run took 133.83 times longer than the fastest. This could mean that an intermediate result is being cached.
96.7 µs ± 224 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [8]:
a = tensor([10., 6, -4])
b = tensor([2., 8, 7])
a + b

tensor([12., 14.,  3.])

In [9]:
a < b

tensor([False,  True,  True])

In [10]:
(a + b).mean().item()

9.666666984558105

In [11]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
m*m

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [12]:
n = tensor([[1., 2, 3], [4,5,6]])
m*n

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [13]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc): c[i,j] = (a[i] * b[:,j]).sum()
    return c

In [14]:
%timeit -n 20 t3 = matmul(m1,m2)

1.05 ms ± 129 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


**Broadcasting Examples**

In [15]:
a = tensor([10., 6, -4])
a > 0

tensor([ True,  True, False])

In [16]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
(m - 5) / 2.73

tensor([[-1.4652, -1.0989, -0.7326],
        [-0.3663,  0.0000,  0.3663],
        [ 0.7326,  1.0989,  1.4652]])

In [17]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3]))

In [18]:
m + c

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [19]:
c.expand_as(m)

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [20]:
t = c.expand_as(m)
t.storage()

/tmp/ipykernel_33/3696445842.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  t.storage()


 10.0
 20.0
 30.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [21]:
t.stride(), t.shape

((0, 1), torch.Size([3, 3]))

In [22]:
c + m

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [23]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6]])
c+m

tensor([[11., 22., 33.],
        [14., 25., 36.]])

In [24]:
c = tensor([10.,20])
m = tensor([[1., 2, 3], [4,5,6]])
c+m

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [25]:
c = tensor([10.,20,30])
c.shape

torch.Size([3])

In [26]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
c+m

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [27]:
c = c.unsqueeze(1)
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3, 1]))

Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

In [28]:
??c.unsqueeze

Docstring:
unsqueeze(dim) -> Tensor

See :func:`torch.unsqueeze`
Type:      builtin_function_or_method

In [29]:
c+m

tensor([[11., 12., 13.],
        [24., 25., 26.],
        [37., 38., 39.]])

In [30]:
t = c.expand_as(m)
t.storage()

 10.0
 20.0
 30.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [31]:
t.stride(), t.shape

((1, 0), torch.Size([3, 3]))

In [32]:
c = tensor([10.,20,30])
c.shape, c.unsqueeze(0).shape,c.unsqueeze(1).shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [33]:
c.shape, c[None,:].shape,c[:,None].shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [34]:
c[None].shape,c[...,None].shape

(torch.Size([1, 3]), torch.Size([3, 1]))

In [35]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
#       c[i,j] = (a[i,:]          * b[:,j]).sum() # previous
        c[i]   = (a[i  ].unsqueeze(-1) * b).sum(dim=0)
    return c

In [37]:
%timeit -n 20 t4 = matmul(m1,m2)

152 µs ± 19.3 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [38]:
def matmul(a,b): return torch.einsum('ik,kj->ij', a, b)

In [39]:
%timeit -n 20 t4 = matmul(m1,m2)

The slowest run took 106.51 times longer than the fastest. This could mean that an intermediate result is being cached.
421 µs ± 965 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


**Building the NN**

In [40]:
def lin(x, w, b): return x @ w + b

In [41]:
x = torch.randn(200, 100)
y = torch.randn(200)

In [42]:
w1 = torch.randn(100,50)
b1 = torch.zeros(50)
w2 = torch.randn(50,1)
b2 = torch.zeros(1)

In [43]:
l1 = lin(x, w1, b1)
l1.shape

torch.Size([200, 50])

In [44]:
l1.mean(), l1.std()

(tensor(-0.0473), tensor(9.8680))

In [45]:
x = torch.randn(200, 100)
for i in range(50): x = x @ torch.randn(100,100)
x[0:5,0:5]

tensor([[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]])

In [46]:
x = torch.randn(200, 100)
for i in range(50): x = x @ (torch.randn(100,100) * 0.01)
x[0:5,0:5]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [47]:
x = torch.randn(200, 100)
for i in range(50): x = x @ (torch.randn(100,100) * 0.1)
x[0:5,0:5]

tensor([[ 0.0049,  0.9053,  0.5875,  0.1328, -0.0061],
        [ 0.2878,  0.2379,  0.6266, -0.3980, -0.1457],
        [-1.9424, -0.7042,  1.9461,  0.3011, -0.8570],
        [-0.3003, -1.3785, -1.5067, -0.2259, -0.1250],
        [-0.3512,  1.3652,  0.3104, -0.2384,  0.5537]])

In [48]:
x.std()

tensor(0.8542)

In [49]:
x = torch.randn(200, 100)
y = torch.randn(200)

In [50]:
from math import sqrt
w1 = torch.randn(100,50) / sqrt(100)
b1 = torch.zeros(50)
w2 = torch.randn(50,1) / sqrt(50)
b2 = torch.zeros(1)

In [51]:
l1 = lin(x, w1, b1)
l1.mean(),l1.std()

(tensor(0.0101), tensor(1.0218))

In [52]:
def relu(x): return x.clamp_min(0.)

In [53]:
l2 = relu(l1)
l2.mean(),l2.std()

(tensor(0.4099), tensor(0.5992))

In [54]:
x = torch.randn(200, 100)
for i in range(50): x = relu(x @ (torch.randn(100,100) * 0.1))
x[0:5,0:5]

tensor([[7.2509e-09, 2.3096e-08, 0.0000e+00, 7.6902e-08, 0.0000e+00],
        [5.1302e-09, 2.2579e-08, 0.0000e+00, 7.2242e-08, 0.0000e+00],
        [4.5195e-09, 2.1011e-08, 0.0000e+00, 8.3214e-08, 1.1771e-09],
        [7.1232e-09, 3.8149e-08, 0.0000e+00, 1.0872e-07, 0.0000e+00],
        [1.1650e-09, 4.2587e-08, 0.0000e+00, 1.1344e-07, 0.0000e+00]])

In [55]:
x = torch.randn(200, 100)
for i in range(50): x = relu(x @ (torch.randn(100,100) * sqrt(2/100)))
x[0:5,0:5]

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 4.1308e-03, 3.6130e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 5.6852e-02, 4.1241e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1393e-02, 4.1719e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.9263e-01, 5.4301e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 2.1952e-02, 2.8560e+00]])

In [56]:
x = torch.randn(200, 100)
y = torch.randn(200)

In [57]:
w1 = torch.randn(100,50) * sqrt(2 / 100)
b1 = torch.zeros(50)
w2 = torch.randn(50,1) * sqrt(2 / 50)
b2 = torch.zeros(1)

In [58]:
l1 = lin(x, w1, b1)
l2 = relu(l1)
l2.mean(), l2.std()

(tensor(0.5660), tensor(0.8304))

In [59]:
def model(x):
    l1 = lin(x, w1, b1)
    l2 = relu(l1)
    l3 = lin(l2, w2, b2)
    return l3

In [60]:
out = model(x)
out.shape

torch.Size([200, 1])

In [61]:
def mse(output, targ): return (output.squeeze(-1) - targ).pow(2).mean()

In [62]:
loss = mse(out, y)

In [63]:
def mse_grad(inp, targ): 
    # grad of loss with respect to output of previous layer
    inp.g = 2. * (inp.squeeze() - targ).unsqueeze(-1) / inp.shape[0]

In [64]:
def relu_grad(inp, out):
    # grad of relu with respect to input activations
    inp.g = (inp>0).float() * out.g

In [65]:
def lin_grad(inp, out, w, b):
    # grad of matmul with respect to input
    inp.g = out.g @ w.t()
    w.g = inp.t() @ out.g
    b.g = out.g.sum(0)

In [67]:
from sympy import symbols,diff
sx,sy = symbols('sx sy')
diff(sx**2, sx)

2*sx

In [68]:
def forward_and_backward(inp, targ):
    # forward pass:
    l1 = inp @ w1 + b1
    l2 = relu(l1)
    out = l2 @ w2 + b2
    # we don't actually need the loss in backward!
    loss = mse(out, targ)
    
    # backward pass:
    mse_grad(out, targ)
    lin_grad(l2, out, w2, b2)
    relu_grad(l1, l2)
    lin_grad(inp, l1, w1, b1)

In [69]:
class Relu():
    def __call__(self, inp):
        self.inp = inp
        self.out = inp.clamp_min(0.)
        return self.out
    
    def backward(self): self.inp.g = (self.inp>0).float() * self.out.g

In [70]:
class Lin():
    def __init__(self, w, b): self.w,self.b = w,b
        
    def __call__(self, inp):
        self.inp = inp
        self.out = inp@self.w + self.b
        return self.out
    
    def backward(self):
        self.inp.g = self.out.g @ self.w.t()
        self.w.g = self.inp.t() @ self.out.g
        self.b.g = self.out.g.sum(0)

In [73]:
class Mse():
    def __call__(self, inp, targ):
        self.inp = inp
        self.targ = targ
        self.out = (inp.squeeze() - targ).pow(2).mean()
        return self.out
    
    def backward(self):
        x = (self.inp.squeeze()-self.targ).unsqueeze(-1)
        self.inp.g = 2.*x/self.targ.shape[0]

In [71]:
class Model():
    def __init__(self, w1, b1, w2, b2):
        self.layers = [Lin(w1,b1), Relu(), Lin(w2,b2)]
        self.loss = Mse()
        
    def __call__(self, x, targ):
        for l in self.layers: x = l(x)
        return self.loss(x, targ)
    
    def backward(self):
        self.loss.backward()
        for l in reversed(self.layers): l.backward()

In [74]:
model = Model(w1, b1, w2, b2)

In [75]:
loss = model(x, y)

In [76]:
model.backward()

In [77]:
class LayerFunction():
    def __call__(self, *args):
        self.args = args
        self.out = self.forward(*args)
        return self.out
    
    def forward(self):  raise Exception('not implemented')
    def bwd(self):      raise Exception('not implemented')
    def backward(self): self.bwd(self.out, *self.args)

In [78]:
class Relu(LayerFunction):
    def forward(self, inp): return inp.clamp_min(0.)
    def bwd(self, out, inp): inp.g = (inp>0).float() * out.g

In [79]:
class Lin(LayerFunction):
    def __init__(self, w, b): self.w,self.b = w,b
        
    def forward(self, inp): return inp@self.w + self.b
    
    def bwd(self, out, inp):
        inp.g = out.g @ self.w.t()
        self.w.g = inp.t() @ self.out.g
        self.b.g = out.g.sum(0)

In [80]:
class Mse(LayerFunction):
    def forward (self, inp, targ): return (inp.squeeze() - targ).pow(2).mean()
    def bwd(self, out, inp, targ): 
        inp.g = 2*(inp.squeeze()-targ).unsqueeze(-1) / targ.shape[0]

In [81]:
from torch.autograd import Function

class MyRelu(Function):
    @staticmethod
    def forward(ctx, i):
        result = i.clamp_min(0.)
        ctx.save_for_backward(i)
        return result
    
    @staticmethod
    def backward(ctx, grad_output):
        i, = ctx.saved_tensors
        return grad_output * (i>0).float()